#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./install.sh [--prefix DIR] [--dry-run] [--skip-config] [--skip-docker] [--skip-services] [--skip-openclaw-install] [--force-overwrite] [--force-config]

Installs a sanitized OpenClaw rebuild repo into a prefix. This script expects
the repo to have been generated by sync.sh from REBUILD-MANIFEST.json.
EOF
}

PREFIX="${OPENCLAW_HOME:-$HOME/.openclaw}"
DRY_RUN=0
SKIP_CONFIG=0
SKIP_DOCKER=0
SKIP_SERVICES=0
SKIP_OPENCLAW_INSTALL=0
FORCE_OVERWRITE=0
FORCE_CONFIG=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --skip-config) SKIP_CONFIG=1; shift ;;
    --skip-docker) SKIP_DOCKER=1; shift ;;
    --skip-services) SKIP_SERVICES=1; shift ;;
    --skip-openclaw-install) SKIP_OPENCLAW_INSTALL=1; shift ;;
    --force-overwrite) FORCE_OVERWRITE=1; shift ;;
    --force-config) FORCE_CONFIG=1; FORCE_OVERWRITE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="$(python3 -c 'import os,sys; print(os.path.abspath(os.path.expanduser(sys.argv[1])))' "$PREFIX")"
WORKSPACE="$PREFIX/workspace"
OPENCLAW_VERSION="$(python3 - "$SCRIPT_DIR/REBUILD-MANIFEST.json" <<'PY'
import json, sys
with open(sys.argv[1], encoding="utf-8") as f:
    print(json.load(f).get("openclaw", {}).get("observed_version", ""))
PY
)"

run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '[dry-run] %q' "$1"
    shift
    for arg in "$@"; do printf ' %q' "$arg"; done
    printf '\n'
  else
    "$@"
  fi
}

render_copy() {
  local src="$1"
  local dest="$2"
  [[ -e "$src" ]] || return 0
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] render-copy $src -> $dest"
    return 0
  fi
  python3 - "$src" "$dest" "$PREFIX" "$WORKSPACE" "$FORCE_OVERWRITE" <<'PY'
import os, shutil, stat, sys
from pathlib import Path

src, dest, prefix, workspace = map(Path, sys.argv[1:5])
force = sys.argv[5] == "1"
home = Path.home()

def render_text(text):
    return (text
        .replace("{{ OPENCLAW_HOME }}", str(prefix))
        .replace("{{ OPENCLAW_WORKSPACE }}", str(workspace))
        .replace("{{ USER_HOME }}", str(home))
        .replace("{{ WRITING_STYLE_FILE }}", str(workspace / "data" / "writing-style.md"))
        .replace("{{ PRIVATE_DATA_DIR }}", str(workspace / "data")))

def is_text(path):
    try:
        path.read_text(encoding="utf-8")
        return True
    except Exception:
        return False

def backup_path(path):
    base = path.with_name(path.name + ".bak")
    candidate = base
    idx = 1
    while candidate.exists():
        candidate = path.with_name(f"{path.name}.bak.{idx}")
        idx += 1
    return candidate

def write_text_preserving(path, text, mode):
    if path.exists():
        try:
            current = path.read_text(encoding="utf-8")
        except Exception:
            current = None
        if current == text:
            os.chmod(path, mode)
            return
        if not force:
            preview = path.with_name(path.name + ".new")
            preview.write_text(text, encoding="utf-8")
            os.chmod(preview, mode)
            print(f"preserved existing {path}; wrote {preview}")
            return
        shutil.copy2(path, backup_path(path))
    path.write_text(text, encoding="utf-8")
    os.chmod(path, mode)

def copy_preserving(src_path, path, mode):
    if path.exists():
        if path.is_file() and src_path.read_bytes() == path.read_bytes():
            os.chmod(path, mode)
            return
        if not force:
            preview = path.with_name(path.name + ".new")
            shutil.copy2(src_path, preview)
            os.chmod(preview, mode)
            print(f"preserved existing {path}; wrote {preview}")
            return
        shutil.copy2(path, backup_path(path))
    shutil.copy2(src_path, path)
    os.chmod(path, mode)

dest.parent.mkdir(parents=True, exist_ok=True)
if src.is_dir():
    for root, dirs, files in os.walk(src):
        rootp = Path(root)
        dirs[:] = [d for d in dirs if not (rootp / d).is_symlink()]
        for name in files:
            p = rootp / name
            if p.is_symlink():
                raise SystemExit(f"refusing to install symlinked source file: {p}")
            rel = p.relative_to(src)
            out = dest / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            mode = stat.S_IMODE(p.stat().st_mode)
            if is_text(p):
                write_text_preserving(out, render_text(p.read_text(encoding="utf-8")), mode)
            else:
                copy_preserving(p, out, mode)
else:
    mode = stat.S_IMODE(src.stat().st_mode)
    if is_text(src):
        write_text_preserving(dest, render_text(src.read_text(encoding="utf-8")), mode)
    else:
        copy_preserving(src, dest, mode)
PY
}

render_config_template() {
  local src="$1"
  local dest="$2"
  local preview="$dest.new"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    if [[ "$FORCE_CONFIG" -eq 1 ]]; then
      echo "[dry-run] render-config $src -> $dest"
    else
      echo "[dry-run] render-config $src -> $preview (active config preserved)"
    fi
    return 0
  fi
  if [[ "$FORCE_CONFIG" -eq 1 ]]; then
    local tmp
    tmp="$(mktemp "${TMPDIR:-/tmp}/openclaw-config.XXXXXX")"
    FORCE_OVERWRITE=1 render_copy "$src" "$tmp"
    if grep -q '{{[^}][^}]*}}' "$tmp"; then
      echo "ERROR: rendered $src still contains unresolved placeholders; refusing to activate $dest" >&2
      rm -f "$tmp"
      exit 2
    fi
    if [[ -e "$dest" ]]; then
      cp -p "$dest" "$dest.bak"
    fi
    mv "$tmp" "$dest"
  else
    render_copy "$src" "$preview"
    echo "Kept active config $dest; review $preview before activating it"
  fi
}

current_openclaw_version() {
  command -v openclaw >/dev/null 2>&1 || return 1
  openclaw --version 2>/dev/null | awk '/OpenClaw/ {print $2; exit}'
}

create_safe_symlink() {
  local target="$1"
  local link="$2"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] ln -sfn $target $link"
    return 0
  fi
  mkdir -p "$(dirname "$link")"
  if [[ -L "$link" ]]; then
    ln -sfn "$target" "$link"
  elif [[ -e "$link" ]]; then
    echo "preserved existing non-symlink $link; wanted symlink to $target"
  else
    ln -s "$target" "$link"
  fi
}

echo "Installing OpenClaw rebuild repo from $SCRIPT_DIR"
echo "Target prefix: $PREFIX"

run mkdir -p "$PREFIX" "$WORKSPACE" "$WORKSPACE/scripts" "$WORKSPACE/openclaw-scripts" "$WORKSPACE/data" "$WORKSPACE/_control"

if [[ "$SKIP_OPENCLAW_INSTALL" -eq 0 && -n "$OPENCLAW_VERSION" ]]; then
  if [[ "$(current_openclaw_version || true)" == "$OPENCLAW_VERSION" ]]; then
    echo "OpenClaw $OPENCLAW_VERSION already available"
  elif [[ "$DRY_RUN" -eq 1 ]]; then
    run npm install -g "openclaw@$OPENCLAW_VERSION"
  else
    if command -v npm >/dev/null 2>&1; then
      run npm install -g "openclaw@$OPENCLAW_VERSION"
    else
      echo "npm not found; cannot install openclaw@$OPENCLAW_VERSION" >&2
      exit 1
    fi
  fi
fi

# Fail loudly when the repo has not been populated by sync.sh --apply:
# render_copy silently skips missing sources, which previously masked an
# empty (tooling-only) repo and produced a no-op "successful" install.
for critical in workspace agents config; do
  if [[ ! -d "$SCRIPT_DIR/$critical" ]] || [[ -z "$(ls -A "$SCRIPT_DIR/$critical" 2>/dev/null)" ]]; then
    echo "ERROR: repo source dir missing/empty: $SCRIPT_DIR/$critical" >&2
    echo "       populate the repo first: ./sync.sh --apply (then review and commit)" >&2
    exit 2
  fi
done

render_copy "$SCRIPT_DIR/workspace" "$WORKSPACE"
render_copy "$SCRIPT_DIR/root-skills" "$PREFIX/skills"
render_copy "$SCRIPT_DIR/hooks" "$PREFIX/hooks"
render_copy "$SCRIPT_DIR/agents" "$PREFIX/agents"
render_copy "$SCRIPT_DIR/extensions" "$PREFIX/extensions"
render_copy "$SCRIPT_DIR/aux-workspaces/workspace-host" "$PREFIX/workspace-host"
render_copy "$SCRIPT_DIR/aux-workspaces/workspace-moltbook" "$PREFIX/workspace-moltbook"
render_copy "$SCRIPT_DIR/aux-workspaces/workspace-review" "$PREFIX/workspace-review"
create_safe_symlink "$WORKSPACE/data/review-queue" "$PREFIX/workspace-review/data/review-queue"
create_safe_symlink "$WORKSPACE/data/reviews" "$PREFIX/workspace-review/data/reviews"
create_safe_symlink "$WORKSPACE/memory" "$PREFIX/workspace-review/memory"
render_copy "$SCRIPT_DIR/aux-workspaces/workspace-sanitizer" "$PREFIX/workspace-sanitizer"
render_copy "$SCRIPT_DIR/aux-workspaces/workspace-moltbook-reviewer" "$PREFIX/workspace-moltbook-reviewer"

if [[ "$SKIP_CONFIG" -eq 0 ]]; then
  render_config_template "$SCRIPT_DIR/config/openclaw.json.template" "$PREFIX/openclaw.json"
  if [[ ! -e "$PREFIX/secrets.json" || "$DRY_RUN" -eq 1 ]]; then
    render_copy "$SCRIPT_DIR/config/secrets.json.template" "$PREFIX/secrets.json"
  else
    echo "Keeping existing $PREFIX/secrets.json"
  fi
  render_copy "$SCRIPT_DIR/config/cron-jobs.json.template" "$PREFIX/cron/jobs.json"
  render_copy "$SCRIPT_DIR/config/plugins-installs.json.template" "$PREFIX/plugins/installs.json"
fi

if [[ "$SKIP_SERVICES" -eq 0 ]]; then
  render_copy "$SCRIPT_DIR/systemd/user" "$HOME/.config/systemd/user"
  if [[ "$DRY_RUN" -eq 0 ]] && command -v systemctl >/dev/null 2>&1; then
    systemctl --user daemon-reload || true
  fi
fi

if [[ "$DRY_RUN" -eq 0 ]]; then
  if [[ ! -d "$WORKSPACE/.git" ]] && command -v git >/dev/null 2>&1; then
    cat > "$WORKSPACE/.gitignore" <<'EOF'
.secrets.json
credentials/
secrets/
data/
memory/
cache/
tmp/
_control/
*.jsonl
*.pdf
*.epub
*.djvu
*.mobi
__pycache__/
.venv/
.local/
node_modules/
EOF
    git -C "$WORKSPACE" init >/dev/null
    git -C "$WORKSPACE" add .gitignore >/dev/null
    git -C "$WORKSPACE" commit -m "Initialize OpenClaw workspace rollback baseline" >/dev/null || true
  fi
fi

if [[ "$SKIP_DOCKER" -eq 0 ]]; then
  echo "Docker setup is intentionally conservative in this MVP."
  echo "Expected images: ghcr.io/hoanganhduc/openclaw-sandbox:latest and sagemath/sagemath:10.8 (arm64: ghcr.io/hoanganhduc/sagemath:10.8)"
fi

if [[ "$DRY_RUN" -eq 0 && -x "$WORKSPACE/scripts/rollback_task.sh" ]]; then
  OPENCLAW_HOME="$PREFIX" OPENCLAW_WORKSPACE="$WORKSPACE" bash "$WORKSPACE/scripts/rollback_task.sh" status || true
fi

echo "install complete"
