#!/usr/bin/bash -p
if [[ "$-" != *p* ]]; then
  exec /usr/bin/bash -p -- "$0" "$@"
fi
set -euo pipefail
umask 077
IFS=$' \t\n'
unset BASH_ENV ENV CDPATH GLOBIGNORE BASH_XTRACEFD PROMPT_COMMAND \
  PYTHONHOME PYTHONPATH PYTHONSTARTUP PYTHONINSPECT PYTHONWARNINGS \
  NODE_OPTIONS NODE_PATH LD_LIBRARY_PATH LD_PRELOAD PERL5OPT RUBYOPT \
  GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
  GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_CONFIG_GLOBAL GIT_CONFIG_SYSTEM
export PATH=/usr/bin:/bin

usage() {
  cat <<'EOF'
Usage: ./install.sh [--prefix DIR] [--destination-prefix DIR] [--services-only]
       [--install-reviewed-services INSTALL_REVIEWED_USER_SERVICES] [--dry-run]
       [--skip-config] [--skip-docker] [--skip-services] [--skip-openclaw-install]
       [--convergent] [--force-overwrite] [--force-config]

Installs a sanitized OpenClaw rebuild repo into a prefix. This script expects
the repo to have been generated by sync.sh from REBUILD-MANIFEST.json.
EOF
}

PREFIX="${OPENCLAW_HOME:-$HOME/.openclaw}"
DESTINATION_PREFIX=""
DRY_RUN=0
SKIP_CONFIG=0
SKIP_DOCKER=0
SKIP_SERVICES=1
INSTALL_REVIEWED_SERVICES=0
SKIP_OPENCLAW_INSTALL=0
FORCE_OVERWRITE=0
FORCE_CONFIG=0
CONVERGENT=0
SERVICES_ONLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2 ;;
    --destination-prefix) DESTINATION_PREFIX="$2"; shift 2 ;;
    --services-only) SERVICES_ONLY=1; shift ;;
    --install-reviewed-services)
      [[ "${2:-}" == "INSTALL_REVIEWED_USER_SERVICES" ]] || {
        echo "service installation requires the exact reviewed-activation token" >&2
        exit 2
      }
      INSTALL_REVIEWED_SERVICES=1; SKIP_SERVICES=0; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --skip-config) SKIP_CONFIG=1; shift ;;
    --skip-docker) SKIP_DOCKER=1; shift ;;
    --skip-services) SKIP_SERVICES=1; shift ;;
    --skip-openclaw-install) SKIP_OPENCLAW_INSTALL=1; shift ;;
    --convergent) CONVERGENT=1; shift ;;
    --force-overwrite) FORCE_OVERWRITE=1; shift ;;
    --force-config) FORCE_CONFIG=1; FORCE_OVERWRITE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="$(/usr/bin/python3 -I -S -B -c 'import os,sys; print(os.path.abspath(os.path.expanduser(sys.argv[1])))' "$PREFIX")"
WORKSPACE="$PREFIX/workspace"
if [[ -z "$DESTINATION_PREFIX" ]]; then
  DESTINATION_PREFIX="$PREFIX"
fi
DESTINATION_PREFIX="$(/usr/bin/python3 -I -S -B -c 'import os,sys; print(os.path.abspath(os.path.expanduser(sys.argv[1])))' "$DESTINATION_PREFIX")"
DESTINATION_WORKSPACE="$DESTINATION_PREFIX/workspace"
OPENCLAW_VERSION="$(/usr/bin/python3 -I -S -B - "$SCRIPT_DIR/REBUILD-MANIFEST.json" <<'PY'
import json, sys
with open(sys.argv[1], encoding="utf-8") as f:
    print(json.load(f).get("openclaw", {}).get("observed_version", ""))
PY
)"

run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '[dry-run] %q' "$1"
    shift
    for arg in "$@"; do printf ' %q' "$arg"; done
    printf '\n'
  else
    "$@"
  fi
}

render_copy() {
  local src="$1"
  local dest="$2"
  local ownership="${3:-managed}"
  [[ -e "$src" ]] || return 0
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] render-copy $src -> $dest"
    return 0
  fi
  /usr/bin/python3 -I -S -B - "$src" "$dest" "$PREFIX" "$WORKSPACE" "$FORCE_OVERWRITE" "$CONVERGENT" "$ownership" <<'PY'
import os, shutil, stat, sys, tempfile
from pathlib import Path

src, dest, prefix, workspace = map(Path, sys.argv[1:5])
force = sys.argv[5] == "1"
convergent = sys.argv[6] == "1"
ownership = sys.argv[7]
home = Path.home()
OWNER_ROOT_FILES = {
    "AGENTS.md", "HEARTBEAT.md", "IDENTITY.md", "MEMORY.md", "SOUL.md",
    "TOOLS.md", "USER.md", "instruction.md",
}

def render_text(text):
    return (text
        .replace("{{ OPENCLAW_HOME }}", str(prefix))
        .replace("{{ OPENCLAW_WORKSPACE }}", str(workspace))
        .replace("{{ USER_HOME }}", str(home))
        .replace("{{ WRITING_STYLE_FILE }}", str(workspace / "data" / "writing-style.md"))
        .replace("{{ PRIVATE_DATA_DIR }}", str(workspace / "data")))

def is_text(path):
    try:
        read_nofollow(path)[0].decode("utf-8")
        return True
    except Exception:
        return False

def lexists(path):
    return os.path.lexists(path)

def open_directory_create(path):
    path = Path(os.path.abspath(path))
    flags = os.O_RDONLY | os.O_DIRECTORY | getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open(path.anchor or os.sep, flags)
    try:
        for component in path.parts[1:]:
            try:
                os.mkdir(component, 0o700, dir_fd=descriptor)
            except FileExistsError:
                pass
            next_descriptor = os.open(component, flags, dir_fd=descriptor)
            os.close(descriptor)
            descriptor = next_descriptor
        return descriptor
    except Exception:
        os.close(descriptor)
        raise

def read_nofollow(path):
    parent = open_directory_create(path.parent)
    descriptor = None
    try:
        path_info = os.stat(path.name, dir_fd=parent, follow_symlinks=False)
        descriptor = os.open(
            path.name,
            os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0),
            dir_fd=parent,
        )
        information = os.fstat(descriptor)
        if (
            not stat.S_ISREG(information.st_mode)
            or information.st_nlink != 1
            or (path_info.st_dev, path_info.st_ino) != (information.st_dev, information.st_ino)
        ):
            raise SystemExit(f"refusing unsafe managed file: {path}")
        chunks = []
        while chunk := os.read(descriptor, 1024 * 1024):
            chunks.append(chunk)
        return b"".join(chunks), stat.S_IMODE(information.st_mode)
    finally:
        if descriptor is not None:
            os.close(descriptor)
        os.close(parent)

def backup_path(path):
    base = path.with_name(path.name + ".bak")
    candidate = base
    idx = 1
    while lexists(candidate):
        information = candidate.lstat()
        if not stat.S_ISREG(information.st_mode) or stat.S_ISLNK(information.st_mode):
            raise SystemExit(f"refusing unsafe backup path: {candidate}")
        candidate = path.with_name(f"{path.name}.bak.{idx}")
        idx += 1
    return candidate

def atomic_write(path, data, mode):
    parent = open_directory_create(path.parent)
    temporary = f".{path.name}.{os.getpid()}.{os.urandom(8).hex()}"
    descriptor = os.open(
        temporary,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
        mode,
        dir_fd=parent,
    )
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, mode, dir_fd=parent, follow_symlinks=False)
        os.replace(temporary, path.name, src_dir_fd=parent, dst_dir_fd=parent)
        os.fsync(parent)
    finally:
        try:
            os.unlink(temporary, dir_fd=parent)
        except FileNotFoundError:
            pass
        os.close(parent)

def preserve_owner_root(path):
    return ownership == "preserve-root" and path.parent == dest and path.name in OWNER_ROOT_FILES

def write_text_preserving(path, text, mode):
    encoded = text.encode("utf-8")
    if lexists(path):
        try:
            current_bytes, current_mode = read_nofollow(path)
            current = current_bytes.decode("utf-8")
        except Exception:
            current = None
        if current == text:
            atomic_write(path, current_bytes, mode)
            return
        if preserve_owner_root(path) and not force:
            print(f"preserved owner-managed {path}")
            return
        if not (force or convergent):
            raise SystemExit(f"existing managed file differs; rerun with --convergent after review: {path}")
        atomic_write(backup_path(path), current_bytes, current_mode)
    atomic_write(path, encoded, mode)

def copy_preserving(src_path, path, mode):
    source_bytes, _source_mode = read_nofollow(src_path)
    if lexists(path):
        current_bytes, current_mode = read_nofollow(path)
        if source_bytes == current_bytes:
            atomic_write(path, current_bytes, mode)
            return
        if preserve_owner_root(path) and not force:
            print(f"preserved owner-managed {path}")
            return
        if not (force or convergent):
            raise SystemExit(f"existing managed file differs; rerun with --convergent after review: {path}")
        atomic_write(backup_path(path), current_bytes, current_mode)
    atomic_write(path, source_bytes, mode)

source_information = src.lstat()
if stat.S_ISLNK(source_information.st_mode):
    raise SystemExit(f"refusing symlinked install source: {src}")
if stat.S_ISDIR(source_information.st_mode):
    for root, dirs, files in os.walk(src):
        rootp = Path(root)
        dirs[:] = [d for d in dirs if not (rootp / d).is_symlink()]
        for name in files:
            p = rootp / name
            if p.is_symlink():
                raise SystemExit(f"refusing to install symlinked source file: {p}")
            rel = p.relative_to(src)
            out = dest / rel
            # Git records executable intent, not group/world write bits. A
            # cooperative checkout umask may therefore materialize 0775/0664;
            # never carry those write permissions into runnable managed files.
            source_payload, source_mode = read_nofollow(p)
            mode = source_mode & ~0o022
            if is_text(p):
                write_text_preserving(out, render_text(source_payload.decode("utf-8")), mode)
            else:
                copy_preserving(p, out, mode)
elif stat.S_ISREG(source_information.st_mode):
    source_payload, source_mode = read_nofollow(src)
    mode = source_mode & ~0o022
    if is_text(src):
        write_text_preserving(dest, render_text(source_payload.decode("utf-8")), mode)
    else:
        copy_preserving(src, dest, mode)
else:
    raise SystemExit(f"refusing special install source: {src}")
PY
}

render_config_template() {
  local src="$1"
  local dest="$2"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    if [[ "$FORCE_CONFIG" -eq 1 ]]; then
      echo "[dry-run] render-config $src -> $dest"
    else
      echo "[dry-run] validate and preserve active config $dest"
    fi
    return 0
  fi
  if [[ "$FORCE_CONFIG" -eq 1 ]]; then
    local tmp
    tmp="$(mktemp "$(dirname -- "$dest")/.openclaw-config.XXXXXX")"
    FORCE_OVERWRITE=1 render_copy "$src" "$tmp"
    if grep -q '{{[^}][^}]*}}' "$tmp"; then
      echo "ERROR: rendered $src still contains unresolved placeholders; refusing to activate $dest" >&2
      rm -f "$tmp"
      exit 2
    fi
    if [[ -L "$dest" ]]; then
      echo "ERROR: refusing symlinked active config $dest" >&2
      exit 2
    fi
    if [[ -e "$dest" ]]; then
      [[ -f "$dest" ]] || { echo "ERROR: active config is not a regular file: $dest" >&2; exit 2; }
      cp -p "$dest" "$dest.bak"
    fi
    mv "$tmp" "$dest"
  else
    if [[ -L "$dest" ]]; then
      echo "ERROR: refusing symlinked active config $dest" >&2
      exit 2
    elif [[ -e "$dest" ]]; then
      [[ -f "$dest" ]] || { echo "ERROR: active config is not a regular file: $dest" >&2; exit 2; }
      /usr/bin/python3 -I -S -B -m json.tool "$dest" >/dev/null
      echo "Kept active config $dest"
    else
      render_copy "$src" "$dest"
    fi
  fi
}

current_openclaw_version() {
  command -v openclaw >/dev/null 2>&1 || return 1
  openclaw --version 2>/dev/null | awk '/OpenClaw/ {print $2; exit}'
}

create_safe_symlink() {
  local target="$1"
  local link="$2"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] ln -sfn $target $link"
    return 0
  fi
  mkdir -p "$(dirname "$link")"
  if [[ -L "$link" ]]; then
    ln -sfn "$target" "$link"
  elif [[ -e "$link" ]]; then
    echo "preserved existing non-symlink $link; wanted symlink to $target"
  else
    ln -s "$target" "$link"
  fi
}

if [[ "$SERVICES_ONLY" -eq 1 ]]; then
  [[ "$INSTALL_REVIEWED_SERVICES" -eq 1 && "$SKIP_SERVICES" -eq 0 ]] || {
    echo "--services-only requires --install-reviewed-services INSTALL_REVIEWED_USER_SERVICES" >&2
    exit 2
  }
  echo "Installing OpenClaw user-service definitions for $PREFIX"
  if [[ "$DRY_RUN" -eq 0 ]]; then
    /usr/bin/python3 -I -S -B "$SCRIPT_DIR/scripts/harden_runtime_ancestors.py" \
      --prefix "$PREFIX"
  fi
  service_args=(--installer-fd 9 --prefix "$PREFIX")
  [[ "$DRY_RUN" -eq 1 ]] && service_args+=(--dry-run)
  /usr/bin/python3 -I -S -B "$SCRIPT_DIR/scripts/service_transaction.py" \
    "${service_args[@]}" 9<"$SCRIPT_DIR/install.sh"
  echo "service install complete"
  exit 0
fi

echo "Installing OpenClaw rebuild repo from $SCRIPT_DIR"
echo "Target prefix: $PREFIX"
if [[ "$DESTINATION_PREFIX" != "$PREFIX" ]]; then
  echo "Staging destination: $DESTINATION_PREFIX"
fi

run mkdir -p "$DESTINATION_PREFIX" "$DESTINATION_WORKSPACE" "$DESTINATION_WORKSPACE/scripts" "$DESTINATION_WORKSPACE/openclaw-scripts" "$DESTINATION_WORKSPACE/data" "$DESTINATION_WORKSPACE/_control"

if [[ "$SKIP_OPENCLAW_INSTALL" -eq 0 && -n "$OPENCLAW_VERSION" ]]; then
  if [[ "$(current_openclaw_version || true)" == "$OPENCLAW_VERSION" ]]; then
    echo "OpenClaw $OPENCLAW_VERSION already available"
  elif [[ "$DRY_RUN" -eq 1 ]]; then
    run npm install -g "openclaw@$OPENCLAW_VERSION"
  else
    if command -v npm >/dev/null 2>&1; then
      run npm install -g "openclaw@$OPENCLAW_VERSION"
    else
      echo "npm not found; cannot install openclaw@$OPENCLAW_VERSION" >&2
      exit 1
    fi
  fi
fi

# Fail loudly when the repo has not been populated by sync.sh --apply:
# render_copy silently skips missing sources, which previously masked an
# empty (tooling-only) repo and produced a no-op "successful" install.
for critical in workspace config; do
  if [[ ! -d "$SCRIPT_DIR/$critical" ]] || [[ -z "$(ls -A "$SCRIPT_DIR/$critical" 2>/dev/null)" ]]; then
    echo "ERROR: repo source dir missing/empty: $SCRIPT_DIR/$critical" >&2
    echo "       populate the repo first: ./sync.sh --apply (then review and commit)" >&2
    exit 2
  fi
done

AUTH_CLOSURE_HELPER="$SCRIPT_DIR/scripts/openclaw_auth_closure.py"
if [[ -f "$AUTH_CLOSURE_HELPER" && ! -L "$AUTH_CLOSURE_HELPER" ]]; then
  placeholder_args=(quarantine-placeholders --prefix "$DESTINATION_PREFIX")
  [[ "$DRY_RUN" -eq 1 ]] && placeholder_args+=(--dry-run)
  /usr/bin/python3 -I -S -B "$AUTH_CLOSURE_HELPER" "${placeholder_args[@]}" >/dev/null
else
  echo "ERROR: OpenClaw auth cleanup helper is missing or unsafe" >&2
  exit 2
fi

render_copy "$SCRIPT_DIR/workspace" "$DESTINATION_WORKSPACE" preserve-root
render_copy "$SCRIPT_DIR/scripts/owner_state_lock.py" \
  "$DESTINATION_WORKSPACE/_control/owner_state_lock.py"
render_copy "$SCRIPT_DIR/root-skills" "$DESTINATION_PREFIX/skills"
render_copy "$SCRIPT_DIR/hooks" "$DESTINATION_PREFIX/hooks"
# Per-agent models/auth files are owner-private runtime state.  Public
# redaction placeholders are valid strings to OpenClaw and therefore create a
# false credential source; never install them from the public component.
render_copy "$SCRIPT_DIR/extensions" "$DESTINATION_PREFIX/extensions"
render_copy "$SCRIPT_DIR/npm" "$DESTINATION_PREFIX/npm"
render_copy "$SCRIPT_DIR/aux-workspaces/workspace-host" "$DESTINATION_PREFIX/workspace-host" preserve-root
render_copy "$SCRIPT_DIR/aux-workspaces/workspace-moltbook" "$DESTINATION_PREFIX/workspace-moltbook" preserve-root
render_copy "$SCRIPT_DIR/aux-workspaces/workspace-review" "$DESTINATION_PREFIX/workspace-review" preserve-root
create_safe_symlink "$WORKSPACE/data/review-queue" "$DESTINATION_PREFIX/workspace-review/data/review-queue"
create_safe_symlink "$WORKSPACE/data/reviews" "$DESTINATION_PREFIX/workspace-review/data/reviews"
create_safe_symlink "$WORKSPACE/memory" "$DESTINATION_PREFIX/workspace-review/memory"
render_copy "$SCRIPT_DIR/aux-workspaces/workspace-sanitizer" "$DESTINATION_PREFIX/workspace-sanitizer" preserve-root
render_copy "$SCRIPT_DIR/aux-workspaces/workspace-moltbook-reviewer" "$DESTINATION_PREFIX/workspace-moltbook-reviewer" preserve-root

if [[ "$SKIP_CONFIG" -eq 0 ]]; then
  render_config_template "$SCRIPT_DIR/config/openclaw.json.template" "$DESTINATION_PREFIX/openclaw.json"
  if [[ ! -e "$DESTINATION_PREFIX/secrets.json" || "$DRY_RUN" -eq 1 ]]; then
    render_copy "$SCRIPT_DIR/config/secrets.json.template" "$DESTINATION_PREFIX/secrets.json"
  else
    echo "Keeping existing $DESTINATION_PREFIX/secrets.json"
  fi
  render_copy "$SCRIPT_DIR/config/cron-jobs.json.template" "$DESTINATION_PREFIX/cron/jobs.json"
  render_copy "$SCRIPT_DIR/config/plugins-installs.json.template" "$DESTINATION_PREFIX/plugins/installs.json"
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "[dry-run] would remove group/world write from credential-reader ancestors"
else
  /usr/bin/python3 -I -S -B "$SCRIPT_DIR/scripts/harden_runtime_ancestors.py" \
    --prefix "$DESTINATION_PREFIX"
fi

if [[ "$SKIP_SERVICES" -eq 0 ]]; then
  service_args=(--installer-fd 9 --prefix "$PREFIX")
  [[ "$DRY_RUN" -eq 1 ]] && service_args+=(--dry-run)
  /usr/bin/python3 -I -S -B "$SCRIPT_DIR/scripts/service_transaction.py" \
    "${service_args[@]}" 9<"$SCRIPT_DIR/install.sh"
fi

if [[ "$DRY_RUN" -eq 0 ]]; then
  if [[ ! -d "$DESTINATION_WORKSPACE/.git" ]] && command -v git >/dev/null 2>&1; then
    cat > "$DESTINATION_WORKSPACE/.gitignore" <<'EOF'
.secrets.json
credentials/
secrets/
data/
memory/
cache/
tmp/
_control/
*.jsonl
*.pdf
*.epub
*.djvu
*.mobi
__pycache__/
.venv/
.local/
.python-closure/
node_modules/
EOF
    git -C "$DESTINATION_WORKSPACE" init >/dev/null
    git -C "$DESTINATION_WORKSPACE" add .gitignore >/dev/null
    git -C "$DESTINATION_WORKSPACE" \
      -c user.name="OpenClaw Restore" \
      -c user.email="openclaw-restore@localhost" \
      commit -m "Initialize OpenClaw workspace rollback baseline" >/dev/null
  fi
  if [[ -d "$DESTINATION_WORKSPACE/.git" && ! -L "$DESTINATION_WORKSPACE/.git" ]]; then
    workspace_exclude="$DESTINATION_WORKSPACE/.git/info/exclude"
    mkdir -p "$(dirname "$workspace_exclude")"
    [[ ! -L "$workspace_exclude" ]] || {
      echo "unsafe workspace Git exclude file: $workspace_exclude" >&2
      exit 2
    }
    touch "$workspace_exclude"
    grep -Fqx '.python-closure/' "$workspace_exclude" \
      || printf '%s\n' '.python-closure/' >> "$workspace_exclude"
  fi
fi

if [[ "$SKIP_DOCKER" -eq 0 ]]; then
  echo "Docker setup is intentionally conservative in this MVP."
  echo "Expected images: ghcr.io/hoanganhduc/coding-system-rebuild-openclaw-sandbox@sha256:f868c49205a1bad3edfbb6a92e1b184f0ab9f7bfe66d11a939d611f081a1f030 and sagemath/sagemath@sha256:e2e4747b0e1ea8753a9cb5a399314a8b2c25fcefaf69ba85b22ee075829d09ea (arm64: ghcr.io/hoanganhduc/sagemath@sha256:6f443fe57534e419c2420d413588e98143429ae9d6cefce7bf026d8d5ff1d793)"
fi

echo "install complete"
